// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace HireRight.Persistence.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReinitWithIntIdsAndStaticIdsAndComputedGuids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReinitWithIntIdsAndStaticIdsAndComputedGuids));
        
        string IMigrationMetadata.Id
        {
            get { return "201803102059033_ReinitWithIntIdsAndStaticIdsAndComputedGuids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
